### ISSUE TITLE
Anbindung an LDAP der Hochschule

### ISSUE THREAD

**Issue by wnck** [florensh/wefactor#1]
Für die Nutzung im Kontext der Hochschule brauchen wir eine LDAP-Anbindung. Hierzu bitte mit mir Kontakt aufnehmen.

**Comment by wnck** [comment]
Hier noch ein paar Infos:

 Informationen über die LDAP-Infrastruktur gibt es unter

https://www.hs-heilbronn.de/422475/ldap-server

Die hochschulinternen Bedingungen zur Anbindung enthält folgende Mail:
========== Zitat =================

Hallo Herr Winckler,

die Freischaltung kann ich erst einrichten, wenn ich mich überzeugt habe, dass der Webserver die Anmeldeseite zwingend per https anbietet und die LDAP-Anbindung per ldaps bzw. ldap mit Start-TLS erfolgt.

Zum Testen verwenden Sie bitte den LDAP-Testserver. Die Daten:

Hostname: ldaps://zld0-master.hs-heilbronn.de (Post 636) Version 3
Basis: dc=hs-heilbronn, dc=de

Falls Sie keine Testbenutzer mehr haben, melden Sie sich bitte nocheinmal.

Das aktuelle CAcert-File mit allen Wurzelzertifikaten finden Sie anbei.

Viele Grüße
Heidrun Schmidt
========== Zitat Ende ============

Ein Testuser ist

``` java
    public static final String TEST_USER1 = "seb10";
    public static final String TEST_USER1_PASSWORD = "dPfd10TS";
```

Ein Beispiel für den LDAP-Zugang findet sich auch in dem LDAP-Projekt in GVS. Im Zweifel bitte bei mir nachfragen.

Für Den Server brauchen wir noch ein Zertifikat (für https). Dazu müssen wir dem Rechner noch einen Namen geben. Ich schlage vor: 

```
wefactor.it.hs-heilbronn.de
```

OK? Wenn ja, dann besorge ich das Zertifikat.

**Comment by wnck** [comment]
Für die Beantragung des Serverzertifikates muss man Zugang zum Rechner haben. Daher kann ich die notwendige Datei nicht anlegen.

Hinweise befolgen auf:
https://www.hs-heilbronn.de/5478192/20_ra_zertifikate_beantragen

**Comment by florensh** [comment]
Ich habe mit Herrn Ballein vereinbart, dass er einen Namen für den Rechner einträgt. Anschließend werde ich ein Zertifikat erstellen.

Wefactor ist soweit vorbereitet für HTTPS und LDAP. Ein lokaler Test gegen den Hochschul-LDAP-Testserver war bereits erfolgreich.

Sobald der Rechnername eingetragen ist werde ich einen Test von der Ubuntu-Maschine aus durchführen und Frau Schmidt Bescheid geben, dass sie sich die Sache mal ansehen kann.

**Comment by wnck** [comment]
Frau Schmidt hat die LDAP-Anbindung mit HTTPS abgesegnet. Sie können ab morgen auf den echten LDAP umstellen. 

Den Zertifikatsantrag habe ich eben unterschrieben. Er läuft leider auf wefactor.se.hs-heilbronn.de. Daher werden wir jetzt erst einmal auf den Namen wefactor.it.hs-heilbronn.de verzichten. Das ist aber kein Problem. Wir wollen erst einmal sehen, ob das Ganze in SEB angenommen wird.

**Comment by florensh** [comment]
WeFactor ist mit dem HS-LDAP-Server verbunden.
